# -*- mode: org; -*-
#+TITLE: Примеры решения задач на Python с сайта pythonist.ru
#+DESCRIPTION:
#+KEYWORDS:
#+AUTHOR:
#+email:
#+INFOJS_OPT:
#+STARTUP:  content

#+DATE: CREATED: <Wed Jun 15 14:11:21 EEST 2022>
# Time-stamp: <Последнее обновление -- Wednesday June 15 19:46:49 EEST 2022>


- [[https://pythonist.ru/primery-resheniya-prostyh-zadach-na-yazyke-python/][Примеры решения простых задач на языке Python с сайта pythonist.ru]] (внешняя ссылка)

** 01. Программа для вычисления среднего значения в заданном списке чисел

   [[https://pythonist.ru/programma-dlya-vychisleniya-srednego-znacheniya-v-zadannom-spiske-chisel/][Ссылка на страничку с задачкой]]

   Программа принимает введенные по одному числа, которые сохраняются в список. Затем она выводит
   среднее значение всех элементов этого списка.

   Моё решение [[file:01_average_value_calculation.py][01_average_value_calculation.py]]

   #+BEGIN_SRC python

   while True:
       try:
           count = int(input('Сколько чисел будем использовать? '))
       except ValueError:
           print('Это не совсем число. Попробуйте снова.')
       else:
           print(f'Вы ввели {count}')
           break


   print('Сейчас я буду запрашивать у Вас числовые значения.')
   a = []


   for i in range(0, count):
       while True:
           try:
               n = int(input('Введите число '))
               a.append(n)
           except ValueError:
               print('Это не совсем число. Попробуйте снова.')
           else:
               break


   average = sum(a) / count
   print('Среднее значение', round(average, 2))

   #+END_SRC

   Это не совсем то решение, которое показано на сайте, здесь реализована проверка на введение
   корректных данных.

** 02. Обмен значений двух переменных

   [[https://pythonist.ru/obmen-znachenij-dvuh-peremennyh/][Ссылка на страничку с задачкой]]

   Данная программа принимает от пользователя два значения и записывает каждое из них в отдельную
   переменную. Затем она меняет местами значения этих переменных без ввода временной переменной.

   Моё решение [[file:02_value_exchange.py][02_value_exchange.py]]

   #+BEGIN_SRC python

   a = input('Первое число ')
   b = input('Второе число ')
   a, b = b, a
   print(f'Первое число {a}')
   print(f'Второе число {b}')

   #+END_SRC

   На сайте приведено какое-то чудноватое решение этой задачки.
   Я сперва подумал, что сделал что-то не то, но затем внизу странички обнаружил примечание
   переводчика.

   Всё я сделал верно. С реализацией проверки на корректные данные заморачиваться не стал.

** 03. Вычисление числа n + nn + nnn при заданном числе n

   [[https://pythonist.ru/vychisleniya-chisla-n-nn-nnn-pri-zadannom-chisle-n/][Ссылка на страничку с задачкой]]

   Программа принимает число n, а затем возвращает сумму вида n + nn + nnn. Здесь nn и nnn
   обозначает повторяющееся 2 или 3 раза число n, записанное в десятичной системе счисления.
   Например, если n = 5, то nn и nnn будут равны 55 и 555 сответственно.

   Моё решение [[file:03_calc_number.py][03_calc_number.py]]

   #+BEGIN_SRC python

   a = []
   n = input('Введите число ')
   a.append(n)
   a.append(n * 2)
   a.append(n * 3)

   print(a)
   print(sum(map(int, a)))

   #+END_SRC

** 04. Программа для написания заданного числа в обратном порядке

   [[https://pythonist.ru/programma-dlya-napisaniya-zadannogo-chisla-v-obratnom-poryadke/][Ссылка на страничку с задачкой]]

   Данная программа получает на вход число и выводит его в «перевернутом» виде (т.е., цифры,
   составляющие введенное число, в результате будут построены в обратном порядке).

   Моё решение [[file:04_number_from_right_to_left.py][04_number_from_right_to_left.py]]

   #+BEGIN_SRC python

   while True:
       number = input("Введите число не менее двузначного: ")
       if not number.isnumeric():
           print("Вы ввели не число. Попробуйте снова: ")
       elif int(number) <= 9:
           print("Мы договаривались, что число будет двухзначное.")
       else:
           print(str(number[::-1]))
           break

   #+END_SRC

   По результату этой задачки требуется пополнить знания о проверке вводимых пользователем данных, в
   том числе и множественной проверки. Завис надолго.

   Сама задачка очень даже лёгкая, но как только стал проверять данные, вскипятил мозг.

   Немного поясню о необходимости проверок:
   - чтобы отобразить вводимые данные наоборот (справа налево) эти данные должны иметь не менее двух
     знаков. Это раз;
   - чтобы сравнить количество знаков вводимых и требуемых. Это два;
   - отобразить нужно числа (по условию), значит нужно проверить вводимые пользователем данные, может
     совсем и не числа он там вводит?! (а буквы?)

**** TODO @todo Изучить способы проверки вводимых данных, также множественные проверки.
