# -*- mode: org; -*-
#+TITLE: ANGRYsearch
#+DESCRIPTION:
#+KEYWORDS:
#+AUTHOR:
#+email:
#+INFOJS_OPT:
#+STARTUP:  content

#+DATE: CREATED: <Wed Jul 28 23:20:32 EEST 2021>
# Time-stamp: <Последнее обновление -- Wednesday July 28 23:21:46 EEST 2021>


* ANGRYsearch (https://github.com/DoTheEvo/ANGRYsearch/)

  /частично описание взято из статьи/
  [[https://omgubuntu.ru/angrysearch/][ANGRYsearch - Быстрый инструмент поиска с графическим интерфейсом для Linux.]]
  Но, насколько я могу судить, эта статья также является переводом описания,
  данного разработчиком к ~ANGRYsearch~.

  ~ANGRYsearch~ — это приложение на основе ~Python~, которое выдает результаты при
  вводе поискового запроса. Общая идея и дизайн приложения основаны на
  инструменте поиска для Windows ~Everything~ (https://www.voidtools.com/).

  ANGRYsearch может отображать результаты поиска так быстро, потому что он
  только индексирует имена файлов. После установки ANGRYsearch вы создаете базу
  данных имен файлов путем индексации вашей системы. Затем ANGRYsearch быстро
  фильтрует имена файлов при вводе запроса.

** Режимы поиска:

   В angrysearch есть 3 режима поиска, по умолчанию выбран ~быстрый~:

   - ~быстрый режим~ - включается, когда установлен флажок рядом с полем ввода.
     Очень быстрый, но без подстрок;

   - ~медленный режим~ - включен, когда флажок снят, он немного медленнее, но
     может найти подстроки даже с нестандартными символами;

   - ~regex mode~ или режим регулярных выражений - активируется клавишей ~F8~,
     обозначается оранжевым цветом фона, самый медленный поиск, подходит для
     очень точного поиска с использованием регулярных выражений, с учетом
     регистра или без него, в отличие от предыдущих режимов поиска, здесь
     ищется не весь путь, а только имена файлов или каталогов.

** Некоторые подробности:

   - база данных находится в ~~/.cache/angrysearch/angry_database.db~;

   - файл конфигурации находится в ~~/.config/angrysearch/angrysearch.conf~;

   - Индексирование файлов может занять ~1 ~2 минуты, в зависимости от того,
     какой жесткий диск вы используете, hdd или ssd, а также файловой системы,
     ntfs в linux намного медленнее. База данных может весить ~ 200 МБ;

   - Не рекомендуется запускать с правами суперпользователя, во-первых, для
     этого нет никаких причин, во-вторых, с такими правами поиск может начать
     сканировать там, где не требуется, например у пользователей Btrfs часто
     сканируются снимки;

   - ~xdg-open~ используется для открытия файлов в зависимости от их ~mime-типа~,
     приложения по умолчанию могут быть установлены в
     ~~/.local/share/Applications/mimeapps.list~ или ~~/.config/mimeapps.list~;

** Установка  и настройка

   зависимости - ~python3-pyqt5~, ~xdg-utils~.

   ~xdg-utils~ есть почти всегда из коробки;

   Ставим ~PyQt5~:

   #+begin_src shell

     emerge dev-python/PyQt5

   #+end_src

   И ставим ANGRYsearch:

   #+begin_src shell

     chmod +x install.sh
     sudo ./install.sh

   #+end_src

   Добавляем обновление базы данных в ~cron~:

   #+begin_src conf

         crontab -e
         #обновление бызы angrysearch
         5 23 * * *	/usr/share/angrysearch/angrysearch_update_database.py

   #+end_src

   Не забываем добавить себя в группу ~cron~.
