# -*- mode: org; -*-
#+TITLE: The Python Workbook ( Ben Stephenson), glava_1
#+DESCRIPTION:
#+KEYWORDS:
#+AUTHOR:
#+email:
#+INFOJS_OPT:
#+STARTUP:  content

#+DATE: CREATED: <Wed Jun 15 12:20:11 EEST 2022>
# Time-stamp: <Последнее обновление -- Wednesday June 15 12:27:12 EEST 2022>


** Упражнение 1. Почтовый адрес (Решено. 9 строк)

   Напишите несколько строк кода, выводящих на экран
   ваше имя и почтовый адрес. Адрес напишите в формате, принятом в вашей стране. Никакого ввода от
   пользователя ваша первая программа принимать не будет, только вывод на экран и больше ничего.

** Упражнение 2. Приветствие (9 строк)

   Напишите программу, запрашивающую у пользователя его имя. В ответ на ввод на экране должно появиться
   приветствие с обращением по имени, введенному с клавиатуры ранее.

** Упражнение 3. Площадь комнаты (Решено. 13 строк)

   Напишите программу, запрашивающую у пользователя длину и ширину комнаты. После ввода значений
   должен быть произведен расчет площади комнаты и выведен на экран. Длина и ширина комнаты должны
   вводиться в формате числа с плавающей запятой. Дополните ввод и вывод единицами измерения,
   принятыми в вашей стране. Это могут быть футы или метры.

** Упражнение 4. Площадь садового участка (Решено. 15 строк)

   Создайте программу, запрашивающую у пользователя длину и ширину садового участка в футах. Выведите
   на экран площадь участка в акрах. Подсказка. В одном акре содержится 43 560 квадратных футов.


** Упражнение 5. Сдаем бутылки (Решено. 15 строк)

   Во многих странах в стоимость стеклотары закладывается определенный депозит, чтобы стимулировать
   покупателей напитков сдавать пустые бутылки. Допустим, бутылки объемом 1 литр и меньше стоят
   $0,10, а бутылки большего объема – $0,25. Напишите программу, запрашивающую у пользователя
   количество бутылок каждого размера. На экране должна отобразиться сумма, которую можно
   выручить, если сдать всю имеющуюся посуду. Отформатируйте вывод так, чтобы сумма включала два
   знака после запятой и дополнялась слева символом доллара.


** Упражнение 6. Налоги и чаевые (Решено. 17 строк)

   Программа, которую вы напишете, должна начинаться с запроса у пользователя суммы заказа в
   ресторане. После этого должен быть произведен расчет налога и чаевых официанту. Вы можете
   использовать принятую в вашем регионе налоговую ставку для подсчета суммы сборов. В качестве чаевых
   мы оставим 18 % от стоимости заказа без учета налога. На выходе программа должна отобразить
   отдельно налог, сумму чаевых и итог, включая обе составляющие. Форматируйте вывод таким образом,
   чтобы все числа отображались с двумя знаками после запятой.
