# -*- mode: org; -*-
#+TITLE: bash-powerline-shell_(ps1_prompt)
#+DESCRIPTION:
#+KEYWORDS:
#+AUTHOR:
#+email:
#+INFOJS_OPT:
#+STARTUP:  content

#+DATE: CREATED: <Sun Jul 25 12:44:39 EEST 2021>
# Time-stamp: <Последнее обновление -- Monday October 4 5:25:22 EEST 2021>




[[https://github.com/abhijitvalluri/bash-powerline-shell][bash-powerline-shell на github]]

** Сразу о недостатке

   В скрипте ~ps1_prompt~ хорошо всё, кроме одного -
   не видно от кого ты работаешь - от ~root~ или от обычного пользователя.

** Описание

   Приглашение в стиле ~Powerline~, написанное на ~bash~.

   Напомню, что ~powerline~ написан на ~python~ и некоторые пользователи считают его
   немного тормознутым или недостаточно быстрым - кому что больше нравится,
   выбирайте.

   - Этот сценарий оболочки в значительной степени полагается на цветовые коды ~ANSI~
     для отображения цветов в окне терминала. Они могут быть непереносимыми, поэтому
     могут не работать для вас прямо из коробки. Возможно, вам потребуется
     установить в ~$TERM~ значение ~xterm-256color~.

   - Кроме того, символы ~Unicode~ требуют использования специального шрифта в вашем
     терминале. Используйте один из шрифтов ~Powerline~, доступных по адресу:
     https://github.com/Lokaltog/powerline-fonts.

   - Шрифт ~DejaVu Sans Mono for Powerline~ кажется одним из лучших шрифтов для
     поддержки Unicode.

   - Вам может потребоваться использовать ~uxterm~, ~XTerm~ с поддержкой ~Unicode~,
     вместо xterm, если символы Unicode отображаются некорректно.

   - Этот скрипт использует ~__git_ps1~, чтобы определить, является ли каталог
     репозиторием ~git~, и если это так, определить имя ветки. Если у вас нет этой
     команды, установите ее для своей системы.

   ~PS~. Доступ к переменным ~__git_ps1~ мы получаем из скрипта ~git-prompt.sh~, который
   устанавливается вместе с ~git~.

** Установка

   - Клонируйте этот репозиторий или скопируйте сценарий оболочки ps1_prompt в
     подходящее место:

   #+begin_src shell

     git clone https://github.com/abhijitvalluri/bash-powerline-shell.git

   #+end_src

   В ~.bashrc~ или ~.profile~ включаем скрипт ~ps1_prompt~:

   #+begin_src conf

         source /usr/share/git/git-prompt.sh
         source ~/ps1_prompt

   #+end_src

** Настройка

   На данный момент у этого сценария нет простой возможности для настройки, кроме
   ручного редактирования по своему вкусу. После того, как вы получите
   представление о сценарии и познакомитесь с цветовыми кодами ANSI, будет довольно
   просто улучшить сценарий по своему вкусу.

   Некоторые ресурсы, которые могут помочь вам в настройке скрипта:

   - https://misc.flogisoft.com/bash/tip_colors_and_formatting

   - [[https://en.wikipedia.org/wiki/ANSI_escape_code#Colors][ANSI color codes]]: - Цветовые коды для ~xterm/uxterm~.

   - [[https://github.com/bits/UTF-8-Unicode-Test-Documents.git][UTF-8 Unicode test documents]]: Используйте тестовые документы в этом репо, чтобы
   увидеть, какие символы отображаются с использованием выбранного вами шрифта.

   - [[https://ss64.com/bash/syntax-prompt.html][PS1 cheat sheet]]: - Подсказка переменных символов для настройки вывода подсказки PS1.
